packageExtensions:
  '@babel/parser@*':
    dependencies:
      '@babel/types': '*'
  '@nodelib/fs.scandir@*':
    dependencies:
      '@types/node': '*'
  '@nodelib/fs.stat@*':
    dependencies:
      '@types/node': '*'
  '@nodelib/fs.walk@*':
    dependencies:
      '@types/node': '*'
  '@octokit/rest@*':
    dependencies:
      '@octokit/core': '*'
  '@theme-ui/theme-provider@*':
    dependencies:
      '@theme-ui/css': '*'
      react: '*'
  fast-glob@*:
    dependencies:
      '@types/node': '*'
  gatsby-cli@*:
    dependencies:
      '@types/react': '*'
  gatsby-link@*:
    dependencies:
      '@types/reach__router': '*'
      react: '*'
  gatsby-plugin-netlify@*:
    dependencies:
      webpack: '*'
  gatsby-source-graphql@*:
    dependencies:
      graphql: '*'
  gatsby-transformer-leasot@*:
    dependencies:
      gatsby: '*'
  gatsby@*:
    dependencies:
      '@types/reach__router': '*'
      '@types/react': '*'
      react: '*'
  theme-ui@*:
    dependencies:
      react: '*'
  unist-util-is@*:
    dependencies:
      '@types/unist': '*'
  'gatsby-plugin-theme-ui@*':
    dependencies:
      'theme-ui': '^0.3.1'
  '@theme-ui/style-guide@*':
    dependencies:
      'theme-ui': '^0.3.1'
  sharp@*:
    devDependencies:
      'node-gyp': '*'
  nan@*:
    devDependencies:
      'node-gyp': '*'
  fsevents@*:
    devDependencies:
      'node-gyp': '*'
  evp_bytestokey@*:
    devDependencies:
      'node-gyp': '*'
#plugins:
#  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
#    spec: "@yarnpkg/plugin-interactive-tools"
