// flow-typed signature: 6c22e38184e973e08b4eee5998232d25
// flow-typed version: <<STUB>>/crop-url_v^2.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crop-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crop-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crop-url/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crop-url/src/index.js' {
  declare module.exports: $Exports<'crop-url/src/index'>;
}
