// flow-typed signature: da4a126b614a76a735ed16c6d3519d17
// flow-typed version: <<STUB>>/gatsby-cli_v^2.5.12

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-cli/lib/create-cli' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/did-you-mean' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/index' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/init-starter' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/reporter/errors' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/reporter/index' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/reporter/prepare-stack-trace' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/reporter/reporters/yurnalist/index' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/util/configstore' {
  declare module.exports: any;
}

declare module 'gatsby-cli/lib/util/is-tty' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-cli/lib/create-cli.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/create-cli'>;
}
declare module 'gatsby-cli/lib/did-you-mean.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/did-you-mean'>;
}
declare module 'gatsby-cli/lib/index.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/index'>;
}
declare module 'gatsby-cli/lib/init-starter.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/init-starter'>;
}
declare module 'gatsby-cli/lib/reporter/errors.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/reporter/errors'>;
}
declare module 'gatsby-cli/lib/reporter/index.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/reporter/index'>;
}
declare module 'gatsby-cli/lib/reporter/prepare-stack-trace.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/reporter/prepare-stack-trace'>;
}
declare module 'gatsby-cli/lib/reporter/reporters/yurnalist/index.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/reporter/reporters/yurnalist/index'>;
}
declare module 'gatsby-cli/lib/util/configstore.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/util/configstore'>;
}
declare module 'gatsby-cli/lib/util/is-tty.js' {
  declare module.exports: $Exports<'gatsby-cli/lib/util/is-tty'>;
}
