// flow-typed signature: 094a8af6e386113f4bcfdee10b8b6906
// flow-typed version: <<STUB>>/gatsby-source-instagram_v^0.5.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-instagram'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-instagram' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-instagram/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-instagram/instagram' {
  declare module.exports: any;
}

declare module 'gatsby-source-instagram/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-instagram/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-instagram/gatsby-node'>;
}
declare module 'gatsby-source-instagram/index' {
  declare module.exports: $Exports<'gatsby-source-instagram'>;
}
declare module 'gatsby-source-instagram/index.js' {
  declare module.exports: $Exports<'gatsby-source-instagram'>;
}
declare module 'gatsby-source-instagram/instagram.js' {
  declare module.exports: $Exports<'gatsby-source-instagram/instagram'>;
}
declare module 'gatsby-source-instagram/normalize.js' {
  declare module.exports: $Exports<'gatsby-source-instagram/normalize'>;
}
