// flow-typed signature: 87490f4a7e24a27a64541e3ea56ffed1
// flow-typed version: <<STUB>>/gatsby-mdx_v^0.6.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-mdx/component-with-mdx-scope' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/constants' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/context' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/feed' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/create-webpack-config' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/on-create-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/on-create-page' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/gatsby/preprocess-source' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/loaders/mdx-components' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/loaders/mdx-loader' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/loaders/mdx-scopes' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/loaders/mdx-wrappers' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/mdx-renderer' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/babel-plugin-gather-exports/index' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/babel-plugin-html-attr-to-jsx-attr' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/babel-plugin-pluck-imports/index' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/create-fake-file-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/create-mdx-node' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/default-options' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/extract-exports' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/gen-mdx' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/get-source-plugins-as-remark-plugins' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/get-table-of-content' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/mdx' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/render-html' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/utils/wrap-root-render-html-entry' {
  declare module.exports: any;
}

declare module 'gatsby-mdx/wrap-root-element' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-mdx/component-with-mdx-scope.js' {
  declare module.exports: $Exports<'gatsby-mdx/component-with-mdx-scope'>;
}
declare module 'gatsby-mdx/constants.js' {
  declare module.exports: $Exports<'gatsby-mdx/constants'>;
}
declare module 'gatsby-mdx/context.js' {
  declare module.exports: $Exports<'gatsby-mdx/context'>;
}
declare module 'gatsby-mdx/feed.js' {
  declare module.exports: $Exports<'gatsby-mdx/feed'>;
}
declare module 'gatsby-mdx/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby-browser'>;
}
declare module 'gatsby-mdx/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby-node'>;
}
declare module 'gatsby-mdx/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby-ssr'>;
}
declare module 'gatsby-mdx/gatsby/create-webpack-config.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/create-webpack-config'>;
}
declare module 'gatsby-mdx/gatsby/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/extend-node-type'>;
}
declare module 'gatsby-mdx/gatsby/on-create-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/on-create-node'>;
}
declare module 'gatsby-mdx/gatsby/on-create-page.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/on-create-page'>;
}
declare module 'gatsby-mdx/gatsby/preprocess-source.js' {
  declare module.exports: $Exports<'gatsby-mdx/gatsby/preprocess-source'>;
}
declare module 'gatsby-mdx/index' {
  declare module.exports: $Exports<'gatsby-mdx'>;
}
declare module 'gatsby-mdx/index.js' {
  declare module.exports: $Exports<'gatsby-mdx'>;
}
declare module 'gatsby-mdx/loaders/mdx-components.js' {
  declare module.exports: $Exports<'gatsby-mdx/loaders/mdx-components'>;
}
declare module 'gatsby-mdx/loaders/mdx-loader.js' {
  declare module.exports: $Exports<'gatsby-mdx/loaders/mdx-loader'>;
}
declare module 'gatsby-mdx/loaders/mdx-scopes.js' {
  declare module.exports: $Exports<'gatsby-mdx/loaders/mdx-scopes'>;
}
declare module 'gatsby-mdx/loaders/mdx-wrappers.js' {
  declare module.exports: $Exports<'gatsby-mdx/loaders/mdx-wrappers'>;
}
declare module 'gatsby-mdx/mdx-renderer.js' {
  declare module.exports: $Exports<'gatsby-mdx/mdx-renderer'>;
}
declare module 'gatsby-mdx/utils/babel-plugin-gather-exports/index.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/babel-plugin-gather-exports/index'>;
}
declare module 'gatsby-mdx/utils/babel-plugin-html-attr-to-jsx-attr.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/babel-plugin-html-attr-to-jsx-attr'>;
}
declare module 'gatsby-mdx/utils/babel-plugin-pluck-imports/index.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/babel-plugin-pluck-imports/index'>;
}
declare module 'gatsby-mdx/utils/create-fake-file-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/create-fake-file-node'>;
}
declare module 'gatsby-mdx/utils/create-mdx-node.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/create-mdx-node'>;
}
declare module 'gatsby-mdx/utils/default-options.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/default-options'>;
}
declare module 'gatsby-mdx/utils/extract-exports.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/extract-exports'>;
}
declare module 'gatsby-mdx/utils/gen-mdx.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/gen-mdx'>;
}
declare module 'gatsby-mdx/utils/get-source-plugins-as-remark-plugins.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/get-source-plugins-as-remark-plugins'>;
}
declare module 'gatsby-mdx/utils/get-table-of-content.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/get-table-of-content'>;
}
declare module 'gatsby-mdx/utils/mdx.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/mdx'>;
}
declare module 'gatsby-mdx/utils/render-html.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/render-html'>;
}
declare module 'gatsby-mdx/utils/wrap-root-render-html-entry.js' {
  declare module.exports: $Exports<'gatsby-mdx/utils/wrap-root-render-html-entry'>;
}
declare module 'gatsby-mdx/wrap-root-element.js' {
  declare module.exports: $Exports<'gatsby-mdx/wrap-root-element'>;
}
