// flow-typed signature: 4897d3c8e9a4fc63d95c538965a7daac
// flow-typed version: <<STUB>>/gatsby-source-git_v^1.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-git/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-git/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-git/gatsby-node'>;
}
declare module 'gatsby-source-git/index' {
  declare module.exports: $Exports<'gatsby-source-git'>;
}
declare module 'gatsby-source-git/index.js' {
  declare module.exports: $Exports<'gatsby-source-git'>;
}
