// flow-typed signature: 7c9b5b0473d27b27c9012eb60636fc3f
// flow-typed version: <<STUB>>/gatsby-transformer-leasot_v^0.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-leasot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-leasot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-leasot/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-leasot/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-leasot/gatsby-node'>;
}
declare module 'gatsby-transformer-leasot/index' {
  declare module.exports: $Exports<'gatsby-transformer-leasot'>;
}
declare module 'gatsby-transformer-leasot/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-leasot'>;
}
