// flow-typed signature: 097dc2bc963646a42be6244485250d6e
// flow-typed version: <<STUB>>/gatsby-source-graphql_v^2.0.18

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-graphql/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-graphql/transforms' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-graphql/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-graphql/gatsby-node'>;
}
declare module 'gatsby-source-graphql/index' {
  declare module.exports: $Exports<'gatsby-source-graphql'>;
}
declare module 'gatsby-source-graphql/index.js' {
  declare module.exports: $Exports<'gatsby-source-graphql'>;
}
declare module 'gatsby-source-graphql/transforms.js' {
  declare module.exports: $Exports<'gatsby-source-graphql/transforms'>;
}
