// flow-typed signature: 166c770eae8ff19ff70cb98c0eec819a
// flow-typed version: <<STUB>>/gatsby-remark-emojis_v^0.3.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-emojis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-emojis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-emojis/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-emojis/index' {
  declare module.exports: $Exports<'gatsby-remark-emojis'>;
}
declare module 'gatsby-remark-emojis/index.js' {
  declare module.exports: $Exports<'gatsby-remark-emojis'>;
}
declare module 'gatsby-remark-emojis/index.spec.js' {
  declare module.exports: $Exports<'gatsby-remark-emojis/index.spec'>;
}
