// flow-typed signature: 67be197fd9ff97bc7a4517fb41efae5c
// flow-typed version: <<STUB>>/gatsby-plugin-root-import_v^2.0.5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-root-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-root-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-root-import/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-root-import/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-root-import/gatsby-node'>;
}
declare module 'gatsby-plugin-root-import/index' {
  declare module.exports: $Exports<'gatsby-plugin-root-import'>;
}
declare module 'gatsby-plugin-root-import/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-root-import'>;
}
