// flow-typed signature: 3f627933648c5e5bcd2896b77c73a211
// flow-typed version: <<STUB>>/gatsby-remark-gemoji-to-emoji_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-gemoji-to-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-gemoji-to-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-gemoji-to-emoji/index' {
  declare module.exports: $Exports<'gatsby-remark-gemoji-to-emoji'>;
}
declare module 'gatsby-remark-gemoji-to-emoji/index.js' {
  declare module.exports: $Exports<'gatsby-remark-gemoji-to-emoji'>;
}
