// flow-typed signature: c367e1824c98f979267463305bcab99a
// flow-typed version: <<STUB>>/gatsby-plugin-dark-mode_v^1.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-dark-mode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-dark-mode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-dark-mode/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-dark-mode/ThemeToggler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-dark-mode/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-dark-mode/gatsby-ssr'>;
}
declare module 'gatsby-plugin-dark-mode/index' {
  declare module.exports: $Exports<'gatsby-plugin-dark-mode'>;
}
declare module 'gatsby-plugin-dark-mode/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-dark-mode'>;
}
declare module 'gatsby-plugin-dark-mode/ThemeToggler.js' {
  declare module.exports: $Exports<'gatsby-plugin-dark-mode/ThemeToggler'>;
}
