// flow-typed signature: 5d96ced973448fbbe011a8b590f3230a
// flow-typed version: <<STUB>>/gatsby-remark-abbr_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-abbr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-abbr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-abbr/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'gatsby-remark-abbr/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-abbr/index' {
  declare module.exports: $Exports<'gatsby-remark-abbr'>;
}
declare module 'gatsby-remark-abbr/index.js' {
  declare module.exports: $Exports<'gatsby-remark-abbr'>;
}
declare module 'gatsby-remark-abbr/src/__tests__/index.js' {
  declare module.exports: $Exports<'gatsby-remark-abbr/src/__tests__/index'>;
}
declare module 'gatsby-remark-abbr/src/index.js' {
  declare module.exports: $Exports<'gatsby-remark-abbr/src/index'>;
}
