// flow-typed signature: b457d9687e718ea02513099319c092f8
// flow-typed version: <<STUB>>/gatsby-plugin-layout_v^1.0.15

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-layout/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-layout/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-layout/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-layout/wrap-page' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-layout/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-layout/gatsby-browser'>;
}
declare module 'gatsby-plugin-layout/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-layout/gatsby-node'>;
}
declare module 'gatsby-plugin-layout/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-layout/gatsby-ssr'>;
}
declare module 'gatsby-plugin-layout/index' {
  declare module.exports: $Exports<'gatsby-plugin-layout'>;
}
declare module 'gatsby-plugin-layout/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-layout'>;
}
declare module 'gatsby-plugin-layout/wrap-page.js' {
  declare module.exports: $Exports<'gatsby-plugin-layout/wrap-page'>;
}
