// flow-typed signature: 658d871da1fe66b5a5f07a36a3d01e0f
// flow-typed version: <<STUB>>/gatsby-plugin-purgecss_v^3.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-purgecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-purgecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-purgecss/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-purgecss/loader' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-purgecss/paths' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-purgecss/shared' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-purgecss/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-purgecss/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss/gatsby-node'>;
}
declare module 'gatsby-plugin-purgecss/index' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss'>;
}
declare module 'gatsby-plugin-purgecss/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss'>;
}
declare module 'gatsby-plugin-purgecss/loader.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss/loader'>;
}
declare module 'gatsby-plugin-purgecss/paths.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss/paths'>;
}
declare module 'gatsby-plugin-purgecss/shared.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss/shared'>;
}
declare module 'gatsby-plugin-purgecss/utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-purgecss/utils'>;
}
