// flow-typed signature: 21d589b5437d8af4d587e22bda7d79ff
// flow-typed version: <<STUB>>/gatsby-theme-context_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-theme-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-theme-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-theme-context/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-theme-context/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-theme-context/ThemeContext' {
  declare module.exports: any;
}

declare module 'gatsby-theme-context/wrapRootElement' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-theme-context/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-theme-context/gatsby-browser'>;
}
declare module 'gatsby-theme-context/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-theme-context/gatsby-ssr'>;
}
declare module 'gatsby-theme-context/index' {
  declare module.exports: $Exports<'gatsby-theme-context'>;
}
declare module 'gatsby-theme-context/index.js' {
  declare module.exports: $Exports<'gatsby-theme-context'>;
}
declare module 'gatsby-theme-context/ThemeContext.js' {
  declare module.exports: $Exports<'gatsby-theme-context/ThemeContext'>;
}
declare module 'gatsby-theme-context/wrapRootElement.js' {
  declare module.exports: $Exports<'gatsby-theme-context/wrapRootElement'>;
}
