// flow-typed signature: fc0542b024fb62ff954ebb79ce38a50e
// flow-typed version: <<STUB>>/gatsby-plugin-react-head_v^0.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-react-head'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-react-head' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-react-head/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-react-head/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-react-head/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-head/gatsby-browser'>;
}
declare module 'gatsby-plugin-react-head/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-head/gatsby-ssr'>;
}
declare module 'gatsby-plugin-react-head/index' {
  declare module.exports: $Exports<'gatsby-plugin-react-head'>;
}
declare module 'gatsby-plugin-react-head/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-head'>;
}
