// flow-typed signature: 86625c23a7acd96e193a014fe8f68d65
// flow-typed version: <<STUB>>/gatsby-remark-a11y-emoji_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-a11y-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-a11y-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-a11y-emoji/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'gatsby-remark-a11y-emoji/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-a11y-emoji/index' {
  declare module.exports: $Exports<'gatsby-remark-a11y-emoji'>;
}
declare module 'gatsby-remark-a11y-emoji/index.js' {
  declare module.exports: $Exports<'gatsby-remark-a11y-emoji'>;
}
declare module 'gatsby-remark-a11y-emoji/src/__tests__/index.js' {
  declare module.exports: $Exports<'gatsby-remark-a11y-emoji/src/__tests__/index'>;
}
declare module 'gatsby-remark-a11y-emoji/src/index.js' {
  declare module.exports: $Exports<'gatsby-remark-a11y-emoji/src/index'>;
}
