// flow-typed signature: e3f5a78f2e500dda9986ea9299be84a3
// flow-typed version: <<STUB>>/gatsby-plugin-netlify-cache_v^1.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-netlify-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-netlify-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-netlify-cache/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-netlify-cache/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cache/gatsby-node'>;
}
declare module 'gatsby-plugin-netlify-cache/index' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cache'>;
}
declare module 'gatsby-plugin-netlify-cache/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cache'>;
}
