// flow-typed signature: 87ed56a6a6d05f8ab48cb98cb493007f
// flow-typed version: <<STUB>>/gatsby-plugin-robots-txt_v^1.4.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-robots-txt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-robots-txt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-robots-txt/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-robots-txt/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-robots-txt/gatsby-node'>;
}
declare module 'gatsby-plugin-robots-txt/index' {
  declare module.exports: $Exports<'gatsby-plugin-robots-txt'>;
}
declare module 'gatsby-plugin-robots-txt/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-robots-txt'>;
}
