// flow-typed signature: 2439c41807217ac91f946c73a3a2c76e
// flow-typed version: <<STUB>>/modern-normalize_v^0.5.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modern-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modern-normalize' {
  declare module.exports: any;
}
