// flow-typed signature: 1059ad0b3f1b5256ee6117f21b4e8807
// flow-typed version: <<STUB>>/nanostyled_v^0.3.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanostyled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanostyled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanostyled/factory' {
  declare module.exports: any;
}

declare module 'nanostyled/index.umd' {
  declare module.exports: any;
}

declare module 'nanostyled/rollup.config' {
  declare module.exports: any;
}

declare module 'nanostyled/src/factory' {
  declare module.exports: any;
}

declare module 'nanostyled/src/index' {
  declare module.exports: any;
}

declare module 'nanostyled/test/benchmark' {
  declare module.exports: any;
}

declare module 'nanostyled/test/nanostyled.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanostyled/factory.js' {
  declare module.exports: $Exports<'nanostyled/factory'>;
}
declare module 'nanostyled/index' {
  declare module.exports: $Exports<'nanostyled'>;
}
declare module 'nanostyled/index.js' {
  declare module.exports: $Exports<'nanostyled'>;
}
declare module 'nanostyled/index.umd.js' {
  declare module.exports: $Exports<'nanostyled/index.umd'>;
}
declare module 'nanostyled/rollup.config.js' {
  declare module.exports: $Exports<'nanostyled/rollup.config'>;
}
declare module 'nanostyled/src/factory.js' {
  declare module.exports: $Exports<'nanostyled/src/factory'>;
}
declare module 'nanostyled/src/index.js' {
  declare module.exports: $Exports<'nanostyled/src/index'>;
}
declare module 'nanostyled/test/benchmark.js' {
  declare module.exports: $Exports<'nanostyled/test/benchmark'>;
}
declare module 'nanostyled/test/nanostyled.test.js' {
  declare module.exports: $Exports<'nanostyled/test/nanostyled.test'>;
}
