// flow-typed signature: 1c497f4ea853b9b596f22bb593cc78f6
// flow-typed version: <<STUB>>/rehype-a11y-emoji_v^0.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-a11y-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rehype-a11y-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rehype-a11y-emoji/index' {
  declare module.exports: $Exports<'rehype-a11y-emoji'>;
}
declare module 'rehype-a11y-emoji/index.js' {
  declare module.exports: $Exports<'rehype-a11y-emoji'>;
}
