// flow-typed signature: d28733944c6634e5d6dbeccab17f50f9
// flow-typed version: <<STUB>>/tailwindcss-accessibility_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss-accessibility'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss-accessibility' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tailwindcss-accessibility/index' {
  declare module.exports: $Exports<'tailwindcss-accessibility'>;
}
declare module 'tailwindcss-accessibility/index.js' {
  declare module.exports: $Exports<'tailwindcss-accessibility'>;
}
