// flow-typed signature: fb768b080e4634317a3aea601f3933ed
// flow-typed version: <<STUB>>/typeface-merriweather_v^0.0.72

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-merriweather'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-merriweather' {
  declare module.exports: any;
}
