// flow-typed signature: b789a76c9424b22e68b08ef5aad5ca4a
// flow-typed version: <<STUB>>/typeface-merriweather-sans_v^0.0.72

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-merriweather-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-merriweather-sans' {
  declare module.exports: any;
}
