// flow-typed signature: 4cf6158a0d1749197e96c003951ac119
// flow-typed version: <<STUB>>/typeface-montserrat_v^0.0.54

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-montserrat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-montserrat' {
  declare module.exports: any;
}
