// flow-typed signature: 7b706a3bd64b3a36695392fccad303af
// flow-typed version: <<STUB>>/typeface-cormorant-garamond_v^0.0.72

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-cormorant-garamond'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-cormorant-garamond' {
  declare module.exports: any;
}
