// flow-typed signature: acc330d6c2f377932dba7ab7bb1e5777
// flow-typed version: <<STUB>>/typeface-proza-libre_v^0.0.72

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-proza-libre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-proza-libre' {
  declare module.exports: any;
}
