// flow-typed signature: cc677237bf8d45e4d1a1b7363ff93b7a
// flow-typed version: <<STUB>>/typography_v^0.16.19

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography/dist/client' {
  declare module.exports: any;
}

declare module 'typography/dist/client.m' {
  declare module.exports: any;
}

declare module 'typography/dist/client.umd' {
  declare module.exports: any;
}

declare module 'typography/dist/index' {
  declare module.exports: any;
}

declare module 'typography/dist/index.m' {
  declare module.exports: any;
}

declare module 'typography/dist/index.umd' {
  declare module.exports: any;
}

declare module 'typography/dist/server' {
  declare module.exports: any;
}

declare module 'typography/dist/server.m' {
  declare module.exports: any;
}

declare module 'typography/dist/server.umd' {
  declare module.exports: any;
}

declare module 'typography/src/client' {
  declare module.exports: any;
}

declare module 'typography/src/index' {
  declare module.exports: any;
}

declare module 'typography/src/utils/compileStyles' {
  declare module.exports: any;
}

declare module 'typography/src/utils/createStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography/dist/client.js' {
  declare module.exports: $Exports<'typography/dist/client'>;
}
declare module 'typography/dist/client.m.js' {
  declare module.exports: $Exports<'typography/dist/client.m'>;
}
declare module 'typography/dist/client.umd.js' {
  declare module.exports: $Exports<'typography/dist/client.umd'>;
}
declare module 'typography/dist/index.js' {
  declare module.exports: $Exports<'typography/dist/index'>;
}
declare module 'typography/dist/index.m.js' {
  declare module.exports: $Exports<'typography/dist/index.m'>;
}
declare module 'typography/dist/index.umd.js' {
  declare module.exports: $Exports<'typography/dist/index.umd'>;
}
declare module 'typography/dist/server.js' {
  declare module.exports: $Exports<'typography/dist/server'>;
}
declare module 'typography/dist/server.m.js' {
  declare module.exports: $Exports<'typography/dist/server.m'>;
}
declare module 'typography/dist/server.umd.js' {
  declare module.exports: $Exports<'typography/dist/server.umd'>;
}
declare module 'typography/src/client.js' {
  declare module.exports: $Exports<'typography/src/client'>;
}
declare module 'typography/src/index.js' {
  declare module.exports: $Exports<'typography/src/index'>;
}
declare module 'typography/src/utils/compileStyles.js' {
  declare module.exports: $Exports<'typography/src/utils/compileStyles'>;
}
declare module 'typography/src/utils/createStyles.js' {
  declare module.exports: $Exports<'typography/src/utils/createStyles'>;
}
