// flow-typed signature: 40565f43e1fc20428556325b74ecf4e2
// flow-typed version: <<STUB>>/typography-theme-github_v^0.16.19

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography-theme-github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography-theme-github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography-theme-github/dist/index' {
  declare module.exports: any;
}

declare module 'typography-theme-github/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography-theme-github/dist/index.js' {
  declare module.exports: $Exports<'typography-theme-github/dist/index'>;
}
declare module 'typography-theme-github/src/index.js' {
  declare module.exports: $Exports<'typography-theme-github/src/index'>;
}
