---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: sites/coding4.gaiama.org/content/posts
  label: Posts
  create: all
  match: "**/*.mdx"
  new_doc_ext: ".mdx"
- type: directory
  path: sites/coding4.gaiama.org/content/pages
  label: Pages
  create: all
  match: "**/*.mdx"
  new_doc_ext: mdx
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
