# based on https://sung.codes/blog/2019/12/25/building-gatsby-with-git-hub-actions-and-deploying-to-netlify/
name: Build and Deploy Releases to Netlify

# TODO: integrate [cache](https://github.com/actions/cache), looks like it's not compatible with actions on.release tho
on:
  push:
    branches:
      - master # only deploy pull requests against master
    paths:
      - '**.jsx?' # only deploy if .js/.jsx files have changed
      - '**.tsx?' # only deploy if .ts/.tsx files have changed
      - '**/yarn.lock' # or dependencies have changed

    # paths-ignore:
    #   - 'docs/**'
  # use https://hub.github.com/hub-release.1.html to trigger a build
  # release:
  #   types:
  #     - created
  # push:
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths
  #   paths-ignore:
  #     - 'docs/**' # to be extended if I decide to enable build on push
  #   branches:
  #     - master
  # 1. Trigger the workflow every 2 hours
  # schedule:
  #   - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 3. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # 3. https://github.com/actions/setup-node
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn
      - run: yarn lerna run build
      - run: yarn workspace @gaiama/coding4.gaiama.org build:live

      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=sites/coding4.gaiama.org/public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
